### PR TITLE
Add new tested device

### PR DESCRIPTION
**Pull request by msva**
New Success Report

### CODE REVIEW

**Comment by MOoDcIRe12** [comment]
Plss oppo a5s

**Comment by MOoDcIRe12** [comment]
Plss oppo a3s

**Comment by basharatr77** [comment]
Plz Oppo F11 Pro Cph-1969 Android 11

**Comment by sanusrider** [comment]
Bro please add root and bootloader to oppo a5s cph1909ex_11_a.46 please sir i want to root it

**Comment by Mihai122172** [comment]
Samsung A21s plizz

**Comment by Mihai122172** [comment]
Samsung A21s plss

**Comment by msva** [comment]
PLEASE, STOP SPAMMING THIS PULL REQUEST WITH YOUR PHONE MODELS

**Pull request merged**
